# Generated by Django 4.1 on 2022-08-31 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['date'], 'verbose_name': 'Partido', 'verbose_name_plural': 'Partidos'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='score',
            field=models.FloatField(blank=True, null=True, verbose_name='Puntuación'),
        ),
    ]
